"""plan_price_created_by_nullable

Revision ID: 9a00f728b184
Revises: 0f1e2d3c4b5a
Create Date: 2026-08-20 10:11:29.837721

Etapa 9d — hueco real encontrado al planificar la migración de datos base
(0017): `PlanPrice.created_by` era NOT NULL (FK a `users.id`), pero en
producción esa migración de datos corre ANTES de que exista ningún usuario
(el primer admin recién se crea después, vía POST /api/setup/admin) — no hay
ningún `user.id` disponible para completarlo. Confirmado con la usuaria
(AskUserQuestion) antes de tocar el modelo: se pasa a nullable en vez de
insertar un usuario "sistema" ficticio. Las filas de `plan_prices` creadas
por la migración de datos quedan con `created_by=NULL` (reviewer
desconocido, es dato de seed); las creadas desde el panel admin (`seed.py`,
`activate_subscription_manually`, etc.) siguen completando `created_by` con
el admin real como hasta ahora.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a00f728b184'
down_revision: Union[str, None] = '0f1e2d3c4b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_prices', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_prices', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
